name: whisper
services:
    whisper:
        container_name: whisper
        volumes:
            - /path/to/your/videos:/videos
        ports:
            - 9003:2147
        image: zhangyiming748/whisper